### ISSUE TITLE
To-do Aug 14

### ISSUE THREAD

**Issue by btupper** [SeascapeScience/gom-series#22]
[ ] Fix analyses vars (Johnathan)

[ ] Map figure (Ben)

[ ] Update surprise plots (ben, CR)

[ ] Human readable names for variables

[ ] Network plots (q25, median, q75) (JE)

[ ] Timeline figure (NR)

[ ] Surprise cartoon figure (NR)

**Comment by jevanilla** [comment]
Copying above items to check off:

- [ ] Fix analyses vars (Johnathan)

- [ ] Map figure (Ben)

- [ ] Update surprise plots (ben, CR)

- [ ] Human readable names for variables (googlesheet ALL)

- [ ] Network plots (q25, median, q75) (JE)

- [ ] Timeline figure (NR)

- [ ] Surprise cartoon figure (NR)

**Comment by jevanilla** [comment]
Analysis vars and corr test updated with PR#23

**Comment by jevanilla** [comment]
In the current target variables: none of the buoys, and only 3 of the Wx. Thats looking nice!

**Comment by btupper** [comment]
OK - I'll look at the target list to match up what is needed.

I forgot to mention that this is using [ggOceansMap](https://mikkovihtakari.github.io/ggOceanMaps/) which works seamlessly (mostly!) with `geom_sf()` and friends.  I would like to see how to produce the same using [marmap](https://github.com/ericpante/marmap/blob/master/vignettes/marmap.pdf)   I didn't have the bandwidth for both, but I decided to use `ggOceansMap` because `marmap` has dependencies on the venerable `sp` and `raster` packages which have been deprecated (sort of) by the respective package authors.

**Comment by btupper** [comment]
OK - the map is trimmed down now with a draft caption [here](https://github.com/SeascapeScience/gom-series/blob/main/readme/README-prettymap.md)

**Comment by SeascapeScience** [comment]
Minor edits... we'll need to change the label names to match our new variable names 
WMCC, EMCC, JB, etc.

**Comment by btupper** [comment]
If you have coordinates I can add them - they question will be, 'are they pretty enough?"

Oh, I'll look for those.

**Comment by SeascapeScience** [comment]
Here are some arrows to try...

[EMCC.csv](https://github.com/SeascapeScience/gom-series/files/12397867/EMCC.csv)
[GBK.csv](https://github.com/SeascapeScience/gom-series/files/12397868/GBK.csv)
[GS.csv](https://github.com/SeascapeScience/gom-series/files/12397869/GS.csv)
[NEC.csv](https://github.com/SeascapeScience/gom-series/files/12397870/NEC.csv)
[SCOT.csv](https://github.com/SeascapeScience/gom-series/files/12397871/SCOT.csv)
[SLOPE.csv](https://github.com/SeascapeScience/gom-series/files/12397872/SLOPE.csv)
[WMCC.csv](https://github.com/SeascapeScience/gom-series/files/12397873/WMCC.csv)

**Comment by SeascapeScience** [comment]
I should say, those files above are lat-lon pairs for the paths of currents. Just to test if we can plot them on. Maybe it would be better to do post?

**Comment by SeascapeScience** [comment]
The abbreviations are in the google sheet that John set up.

**Comment by btupper** [comment]
Ah!  I see.  I'll add them to the regions.pgkg defintions file.  

I'll give the arrows a shake - and then we can decide.

**Comment by SeascapeScience** [comment]
Suggested coordinates:
-72  -62   
39   46

**Comment by btupper** [comment]
Map has new bounding box, revised basin names and currents (unnamed as of yet) - it's getting busy... still need to drop one river station Downeast (I can't spell it).  https://github.com/SeascapeScience/gom-series/blob/main/readme/README-prettymap.md
